### ISSUE TITLE
Slow API startup

### ISSUE THREAD

**Issue by VMelnalksnis** [VMelnalksnis/Gnomeshade#249]
WebApi takes about 2 minutes to startup. Probably an issue with ElasticApm.

**Comment by NicolasREY69330** [comment]
hi @VMelnalksnis I guess I face the exact same behavior, did you disable this param (`AutoRegisterTemplate  = false`) so it solved your problem ?
Many thanks for your help

**Comment by VMelnalksnis** [comment]
Hi @NicolasREY69330 - yes, I think it did, I just check and that was the last change I made to the Elasticsearch sink config here https://github.com/VMelnalksnis/Gnomeshade/blob/f3bc3d5d33098f91e29e3fbd5050cb1d7373503e/source/Gnomeshade.WebApi/Configuration/SerilogHostConfiguration.cs#L72

I don't think I modified anything on Elasticsearch, only updated to newer versions.

Also just checked the startup time - it took about 5 seconds to complete the sink initialization after `ModifyConnectionSettings` completed, and that's with 2 nodes and mTLS certificate authentication.

**Comment by NicolasREY69330** [comment]
Thanks a lot @VMelnalksnis I'll try the same. By the way, I don't even understand the usage of this property, do you?
I found the Serilog setting not that trivial 😬

**Comment by VMelnalksnis** [comment]
@NicolasREY69330 It's this feature in Elasticsearch - https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html
I checkout out the source code a bit, looks like that by default all it does is set the refresh interval, or how soon after indexing the data will be searchable, to 5 seconds. I don't know why it tries to do that by default, I think that this should be configured in Elasticsearch, instead of each app using this sink.

Either way, I didn't see a template with the default name in my cluster, so I guess it didn't even work (could also be because the user didn't have required privileges). Which kind of makes sense, since the 2 minute delay could be some default timeout. If `AutoRegisterTemplate` is set to true, it tries to create the index template in the constructor of the sink. It also does some connection/buffer pool initialization on first request, which uses locks so that this initialization isn't done twice. My guess is that doing this in the constructor, instead when first trying to send logs to Elasticsearch, causes some deadlock, or some connection settings are not correctly setup, so a connection cannot be established. I haven't checked Serilog selflog/failure sink, so maybe that has more info.

**Comment by NicolasREY69330** [comment]
Wow you dig a lot into the stuff, really interesting!
In the coming weeks we plan to simulate in one of our kubernetes env this behavior, and see if the boolean changes something
I'll keep you informed 🙂
